// ── 200 Tips: 20% GenAI, 20% System Design, 20% Patterns, 20% Principal TPM, 20% Soft Skills ──

const TIPS = [
// ── GenAI (40 tips) ──
"🤖 RAG = Retrieve relevant docs → Augment the prompt → Generate answer. Reduces hallucinations by grounding in real data.",
"🤖 Agentic RAG: The agent decides WHEN and WHAT to retrieve, unlike basic RAG which always retrieves blindly.",
"🤖 Fine-tuning changes model behavior/style. RAG adds knowledge. Use RAG first — cheaper and easier to update.",
"🤖 Chunk size for RAG: Too small = lost context. Too large = noise. 512-1024 tokens with 10-20% overlap is a good start.",
"🤖 Vector DB stores embeddings for similarity search. HNSW (fast, memory-heavy) and IVF (slower, memory-efficient) are the main algorithms.",
"🤖 Embedding dimensions: More = more nuance but slower search. 768-1536 is the sweet spot for most use cases.",
"🤖 Guardrails: Input filtering (block prompt injection) + Output filtering (block PII, toxicity). Must-have for production GenAI.",
"🤖 ReAct Pattern: Reason (think) → Act (call tool) → Observe (check result) → Repeat until done.",
"🤖 MCP (Model Context Protocol): Standardized way for LLMs to connect to tools/data. Like USB-C for AI agents.",
"🤖 LangChain = chains of LLM calls. LangGraph = stateful agent graphs with cycles. Use LangGraph for complex agents.",
"🤖 LlamaIndex specializes in data ingestion + retrieval. LangChain specializes in chains + agents. They complement each other.",
"🤖 CrewAI: Define agents with roles + goals + tools. They collaborate autonomously. Great for multi-step workflows.",
"🤖 Prompt Engineering: Chain-of-thought ('think step by step') improves reasoning by 20-40% on complex tasks.",
"🤖 Few-shot prompting: Give 2-3 examples in the prompt. The model mimics the format. Best for consistent output structure.",
"🤖 Temperature: 0 = deterministic, 1 = creative. Use 0 for factual tasks, 0.7 for creative writing.",
"🤖 Hallucinations: LLMs confidently generate false info. Mitigate with RAG, grounding, fact-checking, and confidence scores.",
"🤖 Token limits matter: GPT-4 Turbo = 128K, Claude 3 = 200K, Gemini 1.5 = 1M. But longer context ≠ better retrieval.",
"🤖 Semantic caching: Cache similar (not just identical) queries. Reduces LLM calls by 40-60% for repetitive workloads.",
"🤖 Model Router: Route simple queries to small/cheap models, complex ones to large/expensive. Saves 60-80% on LLM costs.",
"🤖 Ollama runs LLMs locally. `ollama pull llama3.1` then `ollama serve`. 100% free, 100% private. Great for development.",
"🤖 RLHF (Reinforcement Learning from Human Feedback): How ChatGPT was trained to be helpful. Humans rank outputs, model learns preferences.",
"🤖 Structured output: Use JSON mode or function calling to get consistent, parseable responses from LLMs.",
"🤖 Multimodal AI: Models that process text + images + audio. Claude 3, GPT-4V, Gemini all support vision natively.",
"🤖 Evaluation metrics for RAG: Faithfulness (is answer grounded?), Relevance (right docs retrieved?), Answer correctness.",
"🤖 Prompt injection: Malicious input that hijacks the LLM. Defend with input sanitization, system prompts, and output filtering.",
"🤖 Human-in-the-Loop (HITL): AI handles easy cases, escalates uncertain ones. Feedback from humans improves the model over time.",
"🤖 Feature Store: Centralized ML features. Ensures consistency between training and serving. Prevents training-serving skew.",
"🤖 MLOps: CI/CD for ML. Model versioning, A/B testing, monitoring, drift detection. MLflow is the open-source standard.",
"🤖 Hybrid search: Combine keyword (BM25) + semantic (vector) search. Better retrieval than either alone. Used in production RAG.",
"🤖 Re-ranking: After initial retrieval, use a cross-encoder to re-score and reorder results. Improves RAG accuracy by 15-30%.",
"🤖 vLLM: High-throughput LLM serving with PagedAttention. 2-4x faster than naive serving. Standard for production LLM APIs.",
"🤖 Bedrock Knowledge Bases: Managed RAG on AWS. S3 docs → auto-chunking → embeddings → OpenSearch. No infra to manage.",
"🤖 Bedrock Agents: Define tools + instructions, Bedrock handles the ReAct loop. Serverless agent execution.",
"🤖 Bedrock Guardrails: Content filtering, PII redaction, topic denial, hallucination detection. Apply to any Bedrock model.",
"🤖 Tree-of-thought prompting: Explore multiple reasoning paths, evaluate each, pick the best. Better than chain-of-thought for complex problems.",
"🤖 Self-consistency: Generate multiple answers with high temperature, take the majority vote. Improves accuracy on reasoning tasks.",
"🤖 LoRA (Low-Rank Adaptation): Efficient fine-tuning that trains only a small adapter. 10-100x cheaper than full fine-tuning.",
"🤖 Distillation: Train a small model to mimic a large model. Get 80% of GPT-4 quality at 10% of the cost.",
"🤖 AI feedback loop: Deploy → Collect user feedback → Fine-tune/update → Redeploy. Continuous improvement cycle.",
"🤖 Context window ≠ memory. LLMs don't remember past conversations unless you explicitly include them in the prompt.",

// ── System Design (40 tips) ──
"⚙️ CAP Theorem: You can only guarantee 2 of 3 — Consistency, Availability, Partition tolerance. Know which your system picks.",
"⚙️ Horizontal scaling = add more machines. Vertical scaling = bigger machine. Horizontal is preferred but harder to implement.",
"⚙️ Consistent Hashing minimizes key redistribution when nodes are added/removed. Essential for distributed caches and load balancers.",
"⚙️ Fan-out on Write: Push updates to all followers at write time. Fast reads, expensive writes. Used by Twitter for non-celebrities.",
"⚙️ Fan-out on Read: Pull from all followees at read time. Cheap writes, expensive reads. Used for celebrity accounts.",
"⚙️ Database sharding: Hash-based (even distribution), Range-based (range queries), Geo-based (locality). Pick based on access patterns.",
"⚙️ DynamoDB: Single-digit ms latency at any scale. But no joins, limited query patterns. Design access patterns FIRST.",
"⚙️ SQL for complex queries and transactions. NoSQL for scale and flexible schemas. Most systems use both.",
"⚙️ CDN caches static content at edge locations. Reduces latency from 200ms to 20ms for global users. CloudFront, Akamai.",
"⚙️ Load balancer algorithms: Round-robin (simple), Least connections (smart), Consistent hash (sticky). Choose based on workload.",
"⚙️ WebSocket = persistent bidirectional connection. SSE = server-push only. Long polling = client keeps asking. WebSocket for chat.",
"⚙️ Idempotency: Same request, same result. Use idempotency keys for payment APIs. Critical in distributed systems with retries.",
"⚙️ Event-driven architecture: Producers emit events, consumers react. Decoupled, scalable, but harder to debug and trace.",
"⚙️ Kafka: Distributed log. Ordered within partitions. Consumer groups for parallel processing. Retention for replay.",
"⚙️ SQS vs Kafka: SQS = simple queue, managed, auto-scaling. Kafka = log, ordered, replay, higher throughput. Different tools.",
"⚙️ Microservices: Independent deployment, technology diversity, team autonomy. But: network complexity, distributed transactions, debugging.",
"⚙️ API Gateway: Single entry point. Handles auth, rate limiting, routing, request transformation. AWS API Gateway, Kong, Envoy.",
"⚙️ gRPC: Binary protocol, 10x faster than REST for service-to-service. Protocol buffers for schema. Use for internal APIs.",
"⚙️ GraphQL: Client specifies exactly what data it needs. Reduces over-fetching. Great for mobile apps with limited bandwidth.",
"⚙️ Cache invalidation is one of the two hard problems in CS. TTL-based, event-based, or write-through. Pick your poison.",
"⚙️ Redis: In-memory key-value store. Sub-millisecond latency. Use for caching, sessions, rate limiting, leaderboards, pub/sub.",
"⚙️ Active-Active multi-region: Both regions serve traffic. Conflict resolution needed. Last-writer-wins or application-level merge.",
"⚙️ DNS-based load balancing (Route 53): Geo-routing, latency-based, weighted, failover. First layer of global traffic management.",
"⚙️ Bloom Filter: Probabilistic 'is this in the set?' — false positives possible, false negatives impossible. Space-efficient.",
"⚙️ Write-Ahead Log (WAL): Write to log before applying to DB. Ensures durability. Used by PostgreSQL, Kafka, DynamoDB.",
"⚙️ Leader Election: One node coordinates. Raft uses heartbeats + term numbers. If leader fails, new election in milliseconds.",
"⚙️ Distributed lock: Use Redis SETNX or DynamoDB conditional writes. Always set TTL to prevent deadlocks.",
"⚙️ Back-of-envelope estimation: Know your numbers. 1M daily users ≈ 12 req/sec. 1 GB/day ≈ 12 KB/sec.",
"⚙️ S3: 11 nines durability, unlimited storage. Use for data lakes, backups, static hosting. Storage classes for cost optimization.",
"⚙️ Aurora Serverless v2: Auto-scales from 0.5 to 128 ACUs. Pay per second. Great for variable workloads.",
"⚙️ ECS Fargate: Serverless containers. No EC2 to manage. Good for microservices. EKS for Kubernetes-native teams.",
"⚙️ Step Functions: Orchestrate Lambda functions into workflows. Visual designer. Built-in retry and error handling.",
"⚙️ EventBridge: Serverless event bus. Route events between AWS services and SaaS apps. Schema registry for event contracts.",
"⚙️ Geospatial indexing: Geohash (string-based, easy), Quadtree (hierarchical), H3 (hexagonal, Uber uses it). Pick based on query patterns.",
"⚙️ Time-series data: Use Timestream or InfluxDB. Optimized for write-heavy, time-ordered data. Automatic data lifecycle management.",
"⚙️ Graph databases (Neptune): For highly connected data — social networks, fraud detection, knowledge graphs. Cypher or Gremlin queries.",
"⚙️ Data lake vs warehouse: Lake = raw, schema-on-read, cheap. Warehouse = structured, schema-on-write, fast queries. Lakehouse = both.",
"⚙️ Exactly-once processing: Hard in distributed systems. Use idempotent consumers + transactional outbox pattern.",
"⚙️ Service mesh (Istio/Envoy): Handles mTLS, retries, circuit breaking, observability between services. Sidecar pattern.",
"⚙️ OpenTelemetry: Vendor-neutral observability standard. Traces, metrics, logs. Replacing proprietary agents everywhere.",

// ── Design Patterns (40 tips) ──
"🧩 Circuit Breaker: Open → Half-Open → Closed. Prevents cascading failures when a downstream service is unhealthy.",
"🧩 Saga Pattern: Distributed transactions via compensating actions. Choreography (events) vs Orchestration (central coordinator).",
"🧩 CQRS: Separate read and write models. Different databases optimized for each. Sync via events. Worth it for complex domains.",
"🧩 Event Sourcing: Store events, not state. Replay events to rebuild state. Perfect for audit trails and time-travel debugging.",
"🧩 Strangler Fig: Incrementally replace legacy system. Route traffic gradually to new system. Zero big-bang migration risk.",
"🧩 Bulkhead: Isolate failures. Separate thread pools per service. If one pool exhausts, others keep working.",
"🧩 Sidecar: Co-located helper process. Handles logging, proxy, config. Foundation of service mesh architecture.",
"🧩 Backpressure: When consumers can't keep up, slow down producers. Essential for streaming pipelines. Don't drop data silently.",
"🧩 Retry with exponential backoff + jitter: Don't hammer a failing service. Wait 1s, 2s, 4s + random jitter. Prevents thundering herd.",
"🧩 Outbox Pattern: Write event to outbox table in same DB transaction. Separate process publishes to message queue. Guarantees consistency.",
"🧩 API Gateway Pattern: Single entry point for all clients. Handles cross-cutting concerns. Different from reverse proxy.",
"🧩 Backend for Frontend (BFF): Separate API layer per client type (mobile, web, IoT). Each optimized for its client's needs.",
"🧩 Database per Service: Each microservice owns its data. No shared databases. Communicate via APIs or events.",
"🧩 Materialized View: Pre-computed query results stored as a table. Fast reads at the cost of storage and staleness.",
"🧩 Two-Phase Commit (2PC): Coordinator asks all participants to prepare, then commit. Strong consistency but blocks on failure.",
"🧩 Pub/Sub: Publishers emit events, subscribers consume. Decoupled, fan-out. SNS + SQS is the AWS pattern.",
"🧩 Command Query Responsibility Segregation: Commands change state, Queries read state. Separate models, separate scaling.",
"🧩 Rate Limiting patterns: Token bucket (bursty), Sliding window (smooth), Fixed window (simple). Token bucket is most common.",
"🧩 Cache-Aside: Read: check cache → miss → read DB → populate cache. Most common caching pattern. Simple but cache can be stale.",
"🧩 Write-Through: Write to cache AND DB simultaneously. Consistent but slower writes. Good when reads >> writes.",
"🧩 Write-Behind: Write to cache first, async flush to DB. Fast writes but risk of data loss if cache fails.",
"🧩 Leader-Follower: One leader handles writes, followers handle reads. Simple but leader is a bottleneck and SPOF.",
"🧩 Competing Consumers: Multiple consumers read from same queue. Auto-scaling. SQS + Lambda is the serverless version.",
"🧩 Dead Letter Queue: Failed messages go to a separate queue for investigation. Don't lose data, don't block the pipeline.",
"🧩 Throttling: Limit resource usage per client/tenant. Prevent noisy neighbors. Return 429 Too Many Requests.",
"🧩 Health Check: Liveness (is it running?) vs Readiness (can it serve traffic?). Kubernetes uses both. Don't mix them up.",
"🧩 Blue-Green Deployment: Two identical environments. Switch traffic instantly. Easy rollback. But 2x infrastructure cost.",
"🧩 Canary Deployment: Route 1-5% of traffic to new version. Monitor metrics. Gradually increase. Safer than blue-green.",
"🧩 Feature Flags: Toggle features without deployment. A/B testing, gradual rollout, kill switch. LaunchDarkly, AWS AppConfig.",
"🧩 Idempotency Key: Client generates unique key per request. Server deduplicates. Essential for payment APIs and retries.",
"🧩 Transactional Outbox: Atomic write to DB + outbox table. Poller/CDC publishes events. Solves dual-write problem.",
"🧩 Change Data Capture (CDC): Stream DB changes as events. Debezium for PostgreSQL/MySQL. Powers real-time data pipelines.",
"🧩 Ambassador Pattern: Proxy that handles retries, circuit breaking, logging for legacy services. Like a sidecar but for external calls.",
"🧩 Anti-Corruption Layer: Translate between old and new system models. Prevents legacy concepts from leaking into new design.",
"🧩 Choreography: Services react to events independently. No central coordinator. Simple but hard to track overall flow.",
"🧩 Orchestration: Central coordinator directs the workflow. Step Functions, Temporal. Easy to track but coordinator is a dependency.",
"🧩 Scatter-Gather: Send request to multiple services in parallel, aggregate results. Used in search, price comparison.",
"🧩 Priority Queue: Process high-priority items first. Use separate queues per priority level. SQS doesn't support native priority.",
"🧩 Claim Check: Store large payload in S3, pass reference in message. Keeps message queues lean. Common with SQS + S3.",
"🧩 Medallion Architecture: Bronze (raw) → Silver (cleaned) → Gold (business-ready). Standard for lakehouse data pipelines.",

// ── Principal TPM Skills (40 tips) ──
"📋 Always start system design with: requirements → constraints → high-level design → deep dive → trade-offs. Never skip requirements.",
"📋 Quantify impact. Not 'improved performance' but 'reduced p99 latency from 800ms to 200ms, saving $2M/year in compute'.",
"📋 Build vs Buy framework: Build if it's your core differentiator. Buy if it's commodity. Always factor in maintenance cost.",
"📋 Tech debt is not bad — it's a loan. Track it, prioritize it, pay it down strategically. Never ignore it.",
"📋 RFC/Design doc structure: Context → Problem → Proposed Solution → Alternatives Considered → Trade-offs → Timeline → Open Questions.",
"📋 Dependency management: Map all dependencies. Identify critical path. Have weekly syncs with blocking teams. Escalate early.",
"📋 OKRs: Objectives are qualitative and inspiring. Key Results are quantitative and measurable. 70% achievement = good stretch.",
"📋 Roadmap planning: 3-month detail, 6-month direction, 12-month vision. Re-evaluate quarterly. Communicate changes proactively.",
"📋 Risk management: Identify risks early. Rate by probability × impact. Have mitigation plans for top 5. Review weekly.",
"📋 Stakeholder mapping: Who has power? Who has interest? Manage closely (high/high), keep informed (low/high), keep satisfied (high/low).",
"📋 Executive communication: Lead with the ask. Then context. Then data. One page max. No jargon. What do you need them to decide?",
"📋 Program review: Status (Green/Yellow/Red), key metrics, risks, blockers, asks. Keep it under 15 minutes. Written pre-read.",
"📋 Cross-team alignment: Shared goals > shared meetings. Align on outcomes, not outputs. Let teams own their implementation.",
"📋 Influence without authority: Build trust first. Understand their priorities. Frame your ask in terms of their goals.",
"📋 Escalation is not failure. Escalate early with data, options, and your recommendation. Leaders want to help, not be surprised.",
"📋 Post-mortem culture: Blameless. Focus on systems, not people. 5 Whys to find root cause. Action items with owners and dates.",
"📋 Agile at scale: SAFe for large enterprises, LeSS for simpler scaling, Spotify model for autonomous squads. Know the trade-offs.",
"📋 Capacity planning: Forecast growth → model resource needs → plan procurement → buffer 20-30%. Review quarterly.",
"📋 Migration strategy: Strangler fig for gradual. Big bang for simple. Parallel run for critical. Always have a rollback plan.",
"📋 Launch readiness: Checklist covering performance, security, monitoring, runbooks, rollback, on-call, documentation. No shortcuts.",
"📋 Technical strategy: Where are we? Where do we want to be? What's the gap? What's the sequence? What are the dependencies?",
"📋 Cost optimization: Start with visibility (tagging, dashboards). Then right-sizing. Then reserved/savings plans. Then architecture changes.",
"📋 FinOps: Cloud financial management. Teams own their costs. Showback → Chargeback → Optimization. Culture change, not just tools.",
"📋 AI project management: Expect iteration. ML projects are research-like. Set milestones around experiments, not features.",
"📋 Data-driven decisions: Define metrics before building. Instrument everything. A/B test when possible. Correlation ≠ causation.",
"📋 Vendor evaluation: Functionality, cost, lock-in risk, support quality, roadmap alignment, security posture. Weight and score.",
"📋 Architecture review: Is it simple enough? Does it handle failure? Can it scale 10x? Can a new engineer understand it?",
"📋 Documentation: Architecture Decision Records (ADRs) for why. Runbooks for how. README for what. Keep them updated or delete them.",
"📋 On-call culture: Clear escalation paths. Runbooks for common issues. Blameless post-mortems. Rotate fairly. Compensate appropriately.",
"📋 First 90 days as Principal TPM: Listen (30 days) → Quick wins (30 days) → Strategic initiatives (30 days). Build trust before changing things.",
"📋 Saying no: 'Not now' is better than 'no'. Provide alternatives. Show the trade-off. Let the stakeholder make the informed choice.",
"📋 Meeting hygiene: Agenda before. Notes during. Action items after. If no decision needed, it should be an email.",
"📋 Technical credibility: You don't need to code, but you need to understand the code. Read design docs. Ask good questions.",
"📋 Prioritization frameworks: RICE (Reach, Impact, Confidence, Effort), MoSCoW (Must/Should/Could/Won't), ICE (Impact, Confidence, Ease).",
"📋 Stakeholder updates: Frequency matches their level. VP = monthly. Director = bi-weekly. Team = weekly. Adjust based on risk.",
"📋 Program metrics: Velocity, cycle time, defect rate, SLO compliance, dependency resolution time. Track trends, not absolutes.",
"📋 Conflict resolution: Seek to understand first. Find common ground. Focus on interests, not positions. Escalate with options.",
"📋 Team health: Psychological safety > everything. People who feel safe take risks, admit mistakes, and innovate.",
"📋 Innovation time: 20% time, hackathons, tech talks. Structured creativity. Some of the best ideas come from side projects.",
"📋 Succession planning: Document everything. Cross-train team members. If you get hit by a bus, can the program continue?",

// ── Soft Skills (40 tips) ──
"🎯 STAR = Situation, Task, Action, Result. Use it for EVERY behavioral question. No exceptions. Practice until it's automatic.",
"🎯 'Tell me about yourself' — 2 minutes max. Current role → biggest achievement → why this role. Rehearse until natural.",
"🎯 'I don't know but here's how I'd find out' is always better than making something up. Interviewers respect honesty.",
"🎯 Active listening: Repeat back what you heard. 'So what you're asking is...' Shows you understand before you answer.",
"🎯 Pause before answering. 3-5 seconds of silence is fine. It shows you're thinking, not just reacting.",
"🎯 Use 'we' for team achievements, 'I' for your specific contributions. Balance humility with ownership.",
"🎯 Body language matters even on video. Sit up straight. Make eye contact with the camera. Nod to show engagement.",
"🎯 Ask clarifying questions before diving into system design. 'What's the expected scale? Who are the users? What are the constraints?'",
"🎯 When you don't understand a question, ask for clarification. Don't guess and answer the wrong question.",
"🎯 End every answer with impact. Not just what you did, but what changed because of it. Revenue, users, latency, team velocity.",
"🎯 Prepare 8-10 STAR stories covering: leadership, failure, conflict, ambiguity, innovation, scale, influence, customer obsession.",
"🎯 For behavioral questions, be specific. Not 'I usually handle conflict by...' but 'In Q3 2024, when Team X and Team Y disagreed...'",
"🎯 Time your answers. Behavioral: 2-3 minutes. System design: 35 minutes total. Practice with a timer.",
"🎯 Show self-awareness. 'Looking back, I would have done X differently because...' demonstrates growth mindset.",
"🎯 Enthusiasm is contagious. If you're excited about the role, show it. Energy matters in interviews.",
"🎯 Prepare thoughtful questions for the interviewer. 'What's the biggest challenge the team faces?' shows genuine interest.",
"🎯 Handle disagreement gracefully: 'That's an interesting perspective. I see it differently because...' Not 'You're wrong.'",
"🎯 Storytelling: Set the scene briefly, focus on YOUR actions, quantify the result. Cut the backstory if it's not essential.",
"🎯 Adaptability: Show you can change course. 'When the requirements changed mid-project, I...' Rigidity is a red flag.",
"🎯 Empathy in answers: 'I understood their concern was...' shows you consider others' perspectives. Critical for TPM roles.",
"🎯 Conciseness: If you can say it in 30 seconds, don't take 2 minutes. Rambling is the #1 interview killer.",
"🎯 Confidence ≠ arrogance. State your opinions clearly but acknowledge uncertainty. 'I believe X because Y, but I'm open to Z.'",
"🎯 Follow-up questions are a GOOD sign. The interviewer wants to go deeper. Don't panic — they're interested.",
"🎯 Failure stories: Pick real failures with real lessons. 'I learned to always validate assumptions with data before committing resources.'",
"🎯 Influence stories: Show how you changed someone's mind with data and empathy, not authority. TPMs lead through influence.",
"🎯 Scale stories: 'I managed a program with 8 teams across 3 time zones' is more impressive than 'I managed a project.'",
"🎯 Customer obsession: Every answer should connect back to customer impact. 'This reduced customer-facing errors by 40%.'",
"🎯 Bias for action: 'Rather than waiting for perfect information, I made a reversible decision and iterated.' Shows decisiveness.",
"🎯 Earn trust: 'I built credibility by delivering small wins first, then proposed the larger initiative.' Trust is earned, not given.",
"🎯 Disagree and commit: 'I voiced my concerns, the team decided differently, and I fully committed to making it succeed.'",
"🎯 Think big: 'I proposed expanding the project scope from 2 regions to global because the incremental cost was only 20%.'",
"🎯 Dive deep: 'I noticed the p99 latency spike correlated with GC pauses, so I profiled the JVM and tuned the heap settings.'",
"🎯 Simplify: 'I reduced the 47-step deployment process to 3 steps by automating the manual checks.' Simplification is a superpower.",
"🎯 Have backbone: 'I pushed back on the aggressive timeline because cutting testing would risk customer trust. We negotiated 2 extra weeks.'",
"🎯 Ownership: 'It wasn't my team's bug, but it was our customer's problem. I coordinated the fix across 3 teams.'",
"🎯 Deliver results: Every story should end with measurable results. Revenue, cost savings, latency, adoption rate, team velocity.",
"🎯 Frugality: 'I found we could achieve 90% of the goal at 30% of the cost by using managed services instead of building custom.'",
"🎯 Learn and be curious: 'I spent weekends learning Kubernetes because I knew our migration depended on it.' Show initiative.",
"🎯 Hire and develop: 'I mentored two SDEs who later became tech leads. Investing in people multiplies your impact.'",
"🎯 Insist on highest standards: 'I rejected the design because it didn't handle the failure mode we'd seen in production last quarter.'"
];
